### ISSUE TITLE
Add more examples and tests

### ISSUE THREAD

**Issue by sergeyklay** [tajmone/lemon-grove#1]
Hello,

Great work! Do you plan to provide more complete examples and tests?
If not, it is my proposal :)

Thank you

**Comment by tajmone** [comment]
Hi @sergeyklay!

> Great work! Do you plan to provide more complete examples and tests?

Yes, in due time. My plan was to add forks of the original Lemon project, as well as ports to other languages, examples and documents. I'd like to gather together a selection of the best variations on the original Lemon, as well as practical examples.

Wherever possible, I'd like to include third party repositories as Git submodules, unless it makes more sense to just manually include selected files. The problem often boils down to understand the actual status of many lemon-based projects, which don't always state its maturity state.

> If not, it is my proposal :)

Consider it an open-ended project, any proposals a contributions are welcome.

The project will find its shape as we go along — and I'd rather shape the project around contributions and the real needs of Lemon users than enforce a rigid paradigm that is counter-productive to the Lemon userbase.

**Comment by sergeyklay** [comment]
Well, could you setup Travis CI integration? Let's start from simple (empty) build:

```yaml
script:
  - true
```

so that anyone can submit tests via PR and run build/test at Travis CI
