### ISSUE TITLE
New lemon-like project

### ISSUE THREAD

**Issue by rodrigorc** [tajmone/lemon-grove#11]
Please consider adding my new project to your list:

- [Pomelo](https://github.com/rodrigorc/pomelo) (also available at [crates.io](https://crates.io/crates/pomelo)) is a reimplementation of the Lemon parser generator as a Rust procedural macro. It replaces, and eventually deprecates, my previous [lemon_rust](https://github.com/rodrigorc/lemon_rust). It is still in an early stage, but fully functional.

Whether you consider it a _cross-language Lemon_ or a _Lemon inspired_ is up to you. Personally I consider it a _full reimplementation_.

**Comment by tajmone** [comment]
Thanks Rodrigo! I've linked it in  a new section "Lemon Ports", since it's a Lemon reimplementation:

https://github.com/tajmone/lemon-grove/blob/master/README.md#pomelo-rust

When pomelo will replace lemon_rust, let me know, so I can add a note to both entries.
