### ISSUE TITLE
Links are broken

### ISSUE THREAD

**Issue by sergeyklay** [tajmone/lemon-grove#2]
Please take a look at screenshot:

![image](https://user-images.githubusercontent.com/1256298/56689155-240dbc00-66e3-11e9-8418-506f702813d9.png)

**Comment by tajmone** [comment]
Thanks! In my markdown previewer they were working, but apparently the previewer is not 100% GFM compliant, and the TOC generator is not handling well normalization of special chars in headings.

I'll see how I can fix this, for the TOC is autogenerated at save time by a Sublime Text extension.

**Comment by tajmone** [comment]
Mhhh, there doesn't seem a way around this. I've tried alternative settings for the TOC generator, but the problem is that GitHub strips away the injected HTML anchors from the preview.

This is the reason I prefer using AsciiDoc instead, for it handles the TOC automagically, without requiring all these hacks, and provides better formatting. 

I've started porting the document to AsciiDoc, but it's not ready yet (it takes a bit longer to format).

The best solution right now is to reduce the TOC levels to 2 levels, so we just leave out those heading with inline code formatting. Until I find I better solution.

**Comment by tajmone** [comment]
Opened issue on MarkdownTOC repository about GFM incompliancy:

- https://github.com/naokazuterada/MarkdownTOC/issues/139

**Comment by tajmone** [comment]
In any case, I wouldn't worry too nuch about the TOC right now, for this was a temporary document.

I had in mind to swithc to AsciiDoc first, and later on to move some selected documents to a `docs_src/` folder and use [pandoc] an [PP] macros to be able to autoconvert from pandoc markdown both to

1. GFM format, to deploy in the repository as `README.md` docs for browser preview,
2. To HTML docs via templates, in `docs/` folder, which can then be served as a website via GitHub pages (as well as browsable locally).

Pandoc markdow has many more features than GFM, and PP macros can be used to handle both output formats conditionally, and provide good syntax highlighting for the HTML documentation. See my collection of PP macros:

- https://github.com/tajmone/pandoc-goodies/tree/master/pp

Either that, or using Asciidoctor directly (but this wouldn't allow converting also to GFM, which is a pity, for having both would be better).

Having a browsable website associated with the repository is one of the goals, for both documentation and tutorials. By deploying the `docs/` folder from `master` branch we don't even need to maintain a separate `gh-pages` orphan branch, which has the advantage of being able to also deploy copy of the docs in the repos's folder, in GFM.

Of course, it all boils down to finding the time to do it (whish is always in short supply). But on many repositories this model has proven successful for maintaining a nice documentation. Some examples:

- https://github.com/tajmone/polygen-docs
- [Docs HTML Live Preview](http://htmlpreview.github.io/?https://github.com/tajmone/polygen-docs/blob/master/polygen-spec_EN.html)

The point is that by creating a Lemon grammars syntax definition for [Highlight], we can create nice documents. I was hoping to work on that next week.

[Highlight]: https://gitlab.com/saalen/highlight
[pandoc]: https://pandoc.org/
[PP]: https://github.com/CDSoft/pp

**Comment by tajmone** [comment]
Fixed, now we have again a 4-level deep TOC, but all links are working:

- https://github.com/tajmone/lemon-grove/blob/master/lemon/lemon.md

Thanks to Naokazu Terada for the solution:

- naokazuterada/MarkdownTOC#139

**Comment by sergeyklay** [comment]
Thank you!
