### ISSUE TITLE
AsciiDoc vs Markdown

### ISSUE THREAD

**Issue by tajmone** [tajmone/lemon-grove#7]
@sergeyklay, I was considering to use only the GFM markdown format for the README files, and covert `lemon/README.adoc` to markdown.

Even though AsciiDoc offers more features and adds benefits like autogenerated TOCs, admonitions, etc., it might complicate third party contributions, for I'm quite sure that it's not as popular a format as markdown.

I should limit use of AsciiDoc to actual documentation, but stick to GFM for all READMEs and other project related standard documentation files (CHANGELOG, CONTRIBUTING).

Sure, AsciiDoc is one of the officially supported documentation formats on GitHub (along with quite a few others), but there's no doubt that GitHub flavoured markdown is the most popular and widely used format, not to mention easier to learn.

What do you think?

**Comment by sergeyklay** [comment]
My personal point is "it might complicate third party contributions". FYI: I'm from Emacs world. So, there is Org, that is more popular than Markdown. However I think that we can sacrifice some functionality for the sake of providing a standard workflow on GitHub using more recognizable format. We have no reason to surprise users and complicate their aims to contribute.
